Graceful side effects
noted-eip/notes-service pull request #52
Opened 2023-03-08 12:12 UTC by edouard-sn

#### Description

OnAccountDelete: Delete workspace, invites and members reference
DeleteNotes: Delete multiple notes
ListAllNotesInternal: List every notes with ManyNotesFilter
findAll: mongodb repo function
deleteMany: mongodb repo function
updateMany: mongodb repo function

fix GetMember (token.AccountID was used before)

When leaving group or deleting group:
For every note, if the author has a workspace, the note is moved in it, else it is deleted
(everything is "cached" lol)

#### Changelog

Description is the changelog

2023-03-12 05:13 UTC, gabriel654165 requested changes

2023-03-12 08:35 UTC, edouard-sn commented on members.go
> +	memberWorkspace, err := srv.groups.GetWorkspaceInternal(ctx, req.AccountId)
I've already got `UpdateNotesInternal` which takes a `ManyNotesFilter` (so we can choose GroupID, AuthorID or both) and a `UpdateNoteGroupPayload`, is this what you're talking about ?

2023-03-12 08:35 UTC, edouard-sn commented on groups.go
> +	// This type will be used to make only one request to GetWorkspace
I already have a `DeleteNotes` which tkaes a `models.ManyNotesFilter` so you can delete by GroupID, AuthorID, or both (which is pretty convenient in some cases), is this what you mean?

2023-03-12 08:37 UTC, edouard-sn commented on members.go
> +				return nil, statusFromModelError(err) // NOTE: Should we stop everything ?
I actually commited something when you were doing your review which solves this, it's not a loop anymore thanks to `UpdateNotes` and `DeleteNotes`

2023-03-20 04:40 UTC, gabriel654165 approved these changes

2023-03-20 05:44 UTC, merged