Refacto note service
noted-eip/notes-service pull request #9
Opened 2022-10-09 09:08 UTC by gabriel654165

#### Description

Environment variables added in main.go for :
- environment (prod or dev)
- port 
- mongoDbUri (noted database)
- mongoDbName ("notes-service")
- jwtPrivateKey (in order to use the auth package)
- NoteDatabase and NoteCollection (are going to be use in mongo/ methods and initialized in server.go)

Also protobuf style v2 implemented in notes.go, mongo/notes.go and blocks.go, mongo/blocks.go

All methods are returuning ```status.Errorf(codes.Unimplemented, "not implemented")```
In the next PR all methods and enpoints are going to be implemented. But for readable purpose I make this PR first and all the other are going to be based on this PR.

Unit test done and working for empty methods

Fixes #5 
Fixes #6 
Fixes #7 

#### Changelog

- Protobuf style v2 implemented
- Dependancy injection of logger, notes or blocks repository
- Grpc api server

2022-10-10 19:31 UTC, maxime-dodin commented on models/mongo/blocks.go
> +type blockWithIndex struct {
dans quelle cas on vas utiliser le BlockWithIndex à la place du Block ?

2022-10-10 19:32 UTC, maxime-dodin approved these changes

2022-10-11 00:42 UTC, rojas-diego requested changes
Check Discord, I think it's better we take a different approach.

2022-10-11 00:42 UTC, rojas-diego commented on .envServer
> +MONGOO_URI=mongodb://localhost:27017
I'm not sure we should commit the `.env`. Besides, even if these are just for development, let's not commit and push database credentials. WDYT?

2022-10-11 00:42 UTC, rojas-diego commented on Dockerfile
>  FROM alpine:latest
This Dockerfile is outdated/invalid. We don't generate protobuf manually anymore. Refer to the Dockerfile from the accounts service.

2022-10-11 00:42 UTC, rojas-diego commented on Makefile
>  	go mod tidy
I don't see the goal of this rule. `go mod init` should be run once and never again?

2022-10-11 00:42 UTC, rojas-diego commented on Makefile
> +	docker run --rm -v `pwd`/protorepo:/app/protorepo -v `pwd`/misc:/app/misc -w /app noted-go-protoc /bin/sh -c misc/gen_proto.sh
This rule is outdated. We don't generate protobufs manually anymore.

2022-10-11 00:42 UTC, rojas-diego commented on Makefile
>  	docker build -t noted-go-protoc -f misc/Dockerfile .
Same here.

2022-10-11 00:42 UTC, rojas-diego commented on Makefile
> +	docker run -w /app -v `pwd`:/app:ro golangci/golangci-lint golangci-lint run
You deleted the `.golangci.yml` file so maybe this rule doesn't work anymore?

2022-10-11 00:42 UTC, rojas-diego commented on Makefile
> +	docker kill accounts-mongo
Your container should be named `notes-mongo`.

2022-10-11 00:42 UTC, rojas-diego commented on blocks.go
> +type blocksService struct {
Why did you call this `blocksService` if it's a `NotesAPI`?

2022-10-12 15:22 UTC, rojas-diego requested changes
Finished reviewing everything! Neat changes. I just have a few remarks on the implementation of the `models` package, I think it's easier if we hop on a call to discuss those! LMK :)

2022-10-12 15:22 UTC, rojas-diego commented on models/mongo/blocks.go
> +type blockWithIndex struct {
Same question here!

2022-10-12 15:22 UTC, rojas-diego commented on models/mongo/blocks.go
> +}
Why does this exist both in the models and the models.mongo package? Is there any reason for the duplication?

2022-10-12 15:22 UTC, rojas-diego commented on models/mongo/notes.go
> +}
What's the reasoning behind having this `note` structure within the `mongo` package? Can't it be defined within the `models` package and then used by `mongo`?

2022-10-12 15:22 UTC, rojas-diego commented on models/note.go
> +}
Is there such a thing as a note without blocks? What is the purpose of this type?

2022-10-12 15:22 UTC, rojas-diego commented on models/note.go
> +}
Same thing as with the blocks. Using this filter type, you can either target one note by ID or a group of notes (given a user can be the author of multiple notes). I think it's better to have a `NoteFilter` and `ManyNotesFilter` and to differentiate `Delete`, `Get`, `Update` operations (which delete, get and update one single note) and `DeleteMany`, `List` and `UpdateMany` operations. I'm open to talk discuss over Discord if you want.

2022-10-12 15:22 UTC, rojas-diego commented on models/note.go
> +	Update(ctx context.Context, filter *NoteFilter, noteRequest *NoteWithBlocks) error
A call to `Update` should return the updated representation of the object according to REST principles.
```suggestion
	Update(ctx context.Context, filter *NoteFilter, note *NoteWithBlocks) (*NoteWithBlocks, error)
```

2022-10-12 15:22 UTC, rojas-diego commented on main.go
> +	NotesCollection *mongo.Collection = nil
Just realised you have imported some code from the accounts service for that! I guess this is dead code then?

2022-10-12 15:22 UTC, rojas-diego commented on server.go
> +	s.authService = auth.NewService(rawKey)
Looks like you're providing a private key to `auth.NewService` which expects a public key. Happy to discuss it through Discord if you want me to clarify.

2022-11-15 09:10 UTC, merged